version: '3.3'

volumes:
  postgres_data:
  static_volume:
  media_volume:

services:

  db:
    container_name: foodgram_db
    image: postgres:13
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    container_name: foodgram_backend
    image: lartsevka/foodgram_backend:latest
    env_file: .env
    volumes:
      - static_volume:/static
      - media_volume:/app/media
    depends_on:
      - db

  frontend:
    container_name: foodgram_frontend
    image: lartsevka/foodgram_frontend:latest
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
    depends_on:
      - db
      - backend

  gateway:
    container_name: foodgram_gateway
    image: lartsevka/foodgram_gateway:latest
    ports:
      - 9090:80
    volumes:
      - static_volume:/usr/share/nginx/html/
      - media_volume:/app/media:ro
      - ./docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
      - frontend
